### ISSUE TITLE
Allow to configure table schema manually

### ISSUE THREAD

**Issue by mubat** [nvlad/yii2support#197] opened 2018-06-05 14:38 UTC
I take _"missing property"_ inspection alert when have connected 3 table schemas (databases) at Database Windows. But plugin incorrect recognize table schema. 

It would be great to manually set database name at some config.

### Additional info

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm
| IDE Version      | PhpStorm 2018.1.4 Build #PS-181.5087.24, built on May 18, 2018
| Plugin version   | 0.9.54.9
| Yii App Template | advanced

**Comment by nvlad** [comment] 2018-06-05 15:32
Duplicate of #160

**Closed by nvlad** 2018-06-05 15:32 UTC

**Comment by mubat** [comment] 2018-06-06 07:31
I forgot that already describe? :sweat_smile:
