### ISSUE TITLE
Disable Active Record table inspection for abstract classes 

### ISSUE THREAD

**Issue by mubat** [nvlad/yii2support#192] opened 2018-05-22 14:37 UTC
I think, inspection "Undetectable table for ActiveRecord" is redundant to abstract classes.

![screenshot from 2018-05-22 17-35-59](https://user-images.githubusercontent.com/3623986/40369440-a59dffca-5de6-11e8-994a-7a384b985ad7.png)

### Additional info

| Q                | A
| ---------------- | --------
| IDE Name         | PhpStorm
| IDE Version      |  2018.1.4
| Plugin version   | 0.9.50
| Yii App Template | advanced

**Comment by nvlad** [comment] 2018-05-22 16:14
Duplicate issue #159

**Comment by nvlad** [comment] 2018-05-22 16:31
Duplicate of #159

**Closed** 2018-05-23 06:54 UTC
Labels: duplicate
